<a href="https://colab.research.google.com/github/DSPG-2022/Local-Food-Benchmarking/blob/main/prudentproduce_scrape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

html_text = requests.get("https://www.prudentproduce.net/shop/fruit").text
soup = BeautifulSoup(html_text, "lxml")
items = soup.find_all('div', class_ = 'span4 v2shopitem')

dfObj = pd.DataFrame(columns = ["Item Name", "Unit of Measurement", 'Price'])

for item in items:
  item_name = item.find('div', class_ = "smlholder").text.strip()
  item_unit = item.find("div", class_ = "pull-left shopunitsv2").text.strip()
  item_price = item.find("div", class_ = "pull-right shoppricesv3").text.replace(" ", "")
  item_price_list = item_price.split()
  item_price = item_price_list[1] + item_price_list[0]

  dfObj = dfObj.append({"Item Name": item_name, "Unit of Measurement": item_unit, "Price": item_price},
                       ignore_index = True)

In [16]:
dfObj

                       Item Name Unit of Measurement Price
0            Apples, Bag of Gala             3lb bag  6.59
1      Apples, Bag of HoneyCrisp             3lb bag  8.69
2               Apples, Braeburn                each  1.09
3           Apples, Granny Smith                each  1.19
4         Apples, juicing/baking             5lb bag  3.99
5                        Avocado                each  2.29
6                        Bananas                each  0.69
7             Bananas, very ripe                each  0.25
8            Berry, Blackberries                 6oz  4.99
9             Berry, Blueberries                6 oz  4.99
10            Berry, Raspberries                6 oz  4.99
11           Berry, Strawberries                  lb  6.99
12                 Date, Medjool            5 oz bag  2.79
13       Grapefruit, Desert Ruby                each  1.99
14                   Grapes, Red                1 lb  4.59
15                          Kiwi                each  0.99
16                         Lemon                each  1.49
17                         Limes                1-lb  2.99
18                   Mango, Kent                each  1.99
19              Nectarine, White                each  1.50
20              Orange, Valencia                each  1.49
21                Pear, Bartlett                each  1.39
22  Pear, Red and Green, Seconds            3 lb bag  3.99
23             Raisins, Thompson            5 oz bag  1.79
24                Tomato, Cherry                pint  3.25
25                  Tomato, Roma                1-lb  2.50

In [21]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

html_text = requests.get("https://www.prudentproduce.net/shop/vegetables").text
soup = BeautifulSoup(html_text, "lxml")
items = soup.find_all('div', class_ = 'span4 v2shopitem')


for item in items:
  item_name = item.find('div', class_ = "smlholder").text.strip()
  item_unit = item.find("div", class_ = "pull-left shopunitsv2").text.strip()
  item_price = item.find("div", class_ = "pull-right shoppricesv3").text.replace(" ", "")
  item_price_list = item_price.split()
  item_price = item_price_list[1] + item_price_list[0]

  dfObj = dfObj.append({"Item Name": item_name, "Unit of Measurement": item_unit, "Price": item_price},
                       ignore_index = True)

In [26]:
file_name = 'PrudentProduce_sheet.xlsx'
  
# saving the excelsheet
dfObj.to_excel(file_name)